I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 554, in script
    call screen therma_lib_nav
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/script.rpy", line 198, in execute
    screen therma_lib_nav():
  File "game/script.rpy", line 198, in execute
    screen therma_lib_nav():
  File "game/script.rpy", line 199, in execute
    imagebutton auto "therma_lib_pae_%s":
Exception: Imagebutton does not have a idle image. (auto='therma_lib_pae_%s').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 554, in script
    call screen therma_lib_nav
  File "/Applications/renpy-8.0.1-sdk/renpy/ast.py", line 2232, in execute
    self.call("execute")
  File "/Applications/renpy-8.0.1-sdk/renpy/ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Applications/renpy-8.0.1-sdk/renpy/statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Applications/renpy-8.0.1-sdk/renpy/exports.py", line 3161, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/Applications/renpy-8.0.1-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-8.0.1-sdk/renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "/Applications/renpy-8.0.1-sdk/renpy/display/core.py", line 3804, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Applications/renpy-8.0.1-sdk/renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.0.1-sdk/renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.0.1-sdk/renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.0.1-sdk/renpy/display/screen.py", line 451, in visit_all
    callback(self)
  File "/Applications/renpy-8.0.1-sdk/renpy/display/core.py", line 3804, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "/Applications/renpy-8.0.1-sdk/renpy/display/screen.py", line 462, in per_interact
    self.update()
  File "/Applications/renpy-8.0.1-sdk/renpy/display/screen.py", line 653, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 198, in execute
    screen therma_lib_nav():
  File "game/script.rpy", line 198, in execute
    screen therma_lib_nav():
  File "game/script.rpy", line 199, in execute
    imagebutton auto "therma_lib_pae_%s":
  File "/Applications/renpy-8.0.1-sdk/renpy/ui.py", line 952, in _imagebutton
    idle = choice(idle, idle_image, "idle", required=True)
  File "/Applications/renpy-8.0.1-sdk/renpy/ui.py", line 946, in choice
    raise Exception("Imagebutton does not have a %s image. (auto=%r)." % (name, auto))
Exception: Imagebutton does not have a idle image. (auto='therma_lib_pae_%s').

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.1.22070801
Fantasy Ren'py GUI template 1.0
Thu Aug 18 00:39:51 2022
